version: "3"

services:
  db:
    container_name: db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    container_name: api
    build: api/
    volumes:
      - ./api:/app
    depends_on:
      - db
    command: bash -c "crond && exec bundle exec rails s -b '0.0.0.0'"

  front:
    container_name: front
    build: front/
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 8080:3000
